version: "2"

networks:
    bridge:
        driver: bridge
services:
    node:
        build: .
        ports:
            - "3000:3000"
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        command: nodemon index.js
        depends_on:
            - mongo
        links:
            - mongo
        environment:
            - DEBUG=express:*
            - MONGODB_URI=mongo
    mongo:
        image: "mongo:3.4"
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./data/db:/data/db
        command: mongod --smallfiles
        environment:
            - "MONGODB_USER=my_db"
            - "MONGODB_PASS=password!"
